
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
release:
  prerelease: auto
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/naveego/bosun/pkg/core.Version={{.Version}} -X github.com/naveego/bosun/pkg/core.Timestamp={{.Timestamp}} -X github.com/naveego/bosun/pkg/core.Commit={{.ShortCommit}}
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      amd64: amd64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs'
    - '^test'
