# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
    - -s -w -X github.com/naveego/bosun/cmd.Version={{.Version}} -X github.com/naveego/bosun/cmd.Timestamp={{.Timestamp}} -X github.com/naveego/bosun/cmd.Commit={{.ShortCommit}}
  goos:
  - windows
  - linux
  - darwin
  goarch:
  - amd64
archive:
  replacements:
    darwin: darwin
    linux: linux
    windows: windows
    amd64: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
