name: Test setup action
on: [push]
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bosun
        uses: naveego/bosun@master
      - run: echo $BOSUN_CONFIG
      - run: cat $BOSUN_CONFIG
      - run: bosun platform list --verbose
      - run: bosun ws show imports
      - run: bosun --version
      - run: bosun env list
